#!/usr/bin/env python3
from __future__ import print_function
import os
from subprocess import call

home = os.environ["HOME"]
here = os.path.dirname(os.path.abspath(__file__))

linetoadd = "source ~/.bashaux"
found = False

bashrc = os.path.join(home, ".bashrc")
if os.path.exists(bashrc):
    with open(bashrc, "r") as fd:
        for line in fd.readlines():
            if linetoadd in line:
                found = True
                break
else:
    # Create empty bashrc so we can append the source line
    open(bashrc, "a").close()

if not found:
    with open(bashrc, "a") as fd:
        print(linetoadd, file=fd)

with open(os.path.join(home, ".bashaux"), "w") as fd:
    print("""
# Generated by workenv/install.py — re-run install.sh to refresh.
export WORKENV_ROOT="{here}"
export WORKENV_ARCH="$(uname -m)"

# Platform id: arch + libc (e.g. x86_64-glibc-2.35) so host vs container
# toolchains and pip --user installs do not clobber each other.
# Redetect each time this file is sourced (libc can differ after enter/exit container).
unset WORKENV_PLATFORM
if [ -r "$WORKENV_ROOT/bin/workenv-platform.sh" ]; then
    # shellcheck source=/dev/null
    . "$WORKENV_ROOT/bin/workenv-platform.sh"
else
    _libc="$(getconf GNU_LIBC_VERSION 2>/dev/null | sed 's/ /-/g' || true)"
    export WORKENV_PLATFORM="$WORKENV_ARCH-${{_libc:-unknown-libc}}"
    unset _libc
fi
export WORKENV_PREFIX="$WORKENV_ROOT/$WORKENV_PLATFORM"

# pip install --user and user site-packages (native wheels are libc-bound).
# Always align with platform when unset or still on the default ~/.local tree.
if [ -z "${{PYTHONUSERBASE:-}}" ] || [ "$PYTHONUSERBASE" = "$HOME/.local" ]; then
    export PYTHONUSERBASE="$HOME/.local/$WORKENV_PLATFORM"
fi

# Platform-specific toolchain (Python, vim, clangd, shared libs)
if [ -d "$WORKENV_PREFIX/lib" ]; then
    export LD_LIBRARY_PATH="$WORKENV_PREFIX/lib${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
fi
if [ -d "$WORKENV_PREFIX/lib64" ]; then
    export LD_LIBRARY_PATH="$WORKENV_PREFIX/lib64${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
fi
# Legacy single-tree layout (pre multi-arch)
if [ -d "$WORKENV_ROOT/lib" ]; then
    export LD_LIBRARY_PATH="$WORKENV_ROOT/lib${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
fi
if [ -d "$WORKENV_ROOT/lib64" ]; then
    export LD_LIBRARY_PATH="$WORKENV_ROOT/lib64${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
fi

if [ -d ~/venv ]
then
    source ~/venv/bin/activate
fi

set -o vi

# Platform toolchain first (python/vim/clangd), then portable scripts, then user bins.
# Platform first so a leftover bin/python from an old install cannot shadow the good one.
export PATH="$WORKENV_PREFIX/bin:$WORKENV_ROOT/bin:$HOME/bin:$PATH"
export PATH="$PATH:$PYTHONUSERBASE/bin"

if [ -d "$WORKENV_ROOT/py" ]
then
    export PYTHONPATH="$WORKENV_ROOT/py${{PYTHONPATH:+:$PYTHONPATH}}"
fi

if [ -d ~/repos/workenv/py ]
then
    export PYTHONPATH="$HOME/repos/workenv/py${{PYTHONPATH:+:$PYTHONPATH}}"
fi

if [ -d ~/venv/ ]
then
    export PYTHON_HOME="$HOME/venv"
    export PATH="$HOME/venv/bin:$PATH"
fi

alias vi=vim
alias unify="spack config add concretizer:unify:true"
alias reuse="spack config add concretizer:reuse:true"
alias vdiff="vimdiff -c 'set wrap' -c 'wincmd w' -c 'set wrap'"
alias twait='fg && trun -n echo success || trun -n echo failure'
alias spack-load='source spack-load.sh'
alias show-cursor='echo -en "\033[?25h"'
#alias show-cursor='echo -en "\\x1b[?25h"'
alias today='date +%m-%d-%Y'
alias pip3='python3 -m pip'
alias gitup='git pull --rebase origin'

function set-title() {{
  if [[ -z "$ORIG" ]]; then
    ORIG=$PS1
  fi
  TITLE="\\[\033]2;$*\\a\\]"
  #TITLE="\\[\x1b]2;$*\\a\\]"
  PS1=${{ORIG}}${{TITLE}}
}}

#function set-title() {{
#    printf "\033]2;$*\\a"
#    printf "\x1b]2;$*\\a"
#}}

if [ -r /usr/bin/hostname -o -r /bin/hostname ]
then
  HOST=$(hostname)
else
  HOST=""
fi
if [ "$HOST" = "" ] && [ -r /usr/bin/uname -o -r /bin/uname ]
then
  HOST=$(uname -n)
fi
if [ "$HOST" = "" ] && [ -r /etc/hostname ]
then
  HOST=$(cat /etc/hostname)
fi
if [ "$HOST" = "" ]
then
  HOST=Linux
fi
if [ "$(id -u)" = 0 ]
then
    export PS1_COLOR='\\[\\033[33m\\]$HOST \\[\\033[93m\\]$(basename "$PWD")\\[\\033[0m\\]# '
    export PS1_BW='$HOST $(basename "$PWD")# '
    PS1=$PS1_COLOR
else
    export PS1_COLOR='\\[\\033[36m\\]$HOST \\[\\033[32m\\]$(basename "$PWD")\\[\\033[0m\\]$ '
    export PS1_BW='$HOST $(basename "$PWD")$ '
    PS1=$PS1_COLOR
fi
alias ps1color='PS1=$PS1_COLOR'
alias ps1bw='PS1=$PS1_BW'
unset PROMPT_COMMAND
export OMP_NUM_THREADS=1
export LANG=en_US.UTF-8
if command -v vim >/dev/null 2>&1; then
  export VISUAL="$(command -v vim)"
fi

export HISTCONTROL=erasedups
export HISTIGNORE="cd:pwd:ls:exit:clear:history*:#*"

# append to the history file, don't overwrite it
shopt -s histappend

# Unlimited in-memory and on-disk history (bash 4.3+: negative = no limit)
export HISTSIZE=-1
export HISTFILESIZE=-1

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
#shopt -s checkwinsize

# git pull + install.sh (install.sh prompts on /dev/tty before Python/Vim).
# Flags are passed through: envup --skip-python, envup -y, envup --force-python, …
# Use "function" keyword — required on some cluster bash builds for this definition form.
function envup {{
  local _envup_pwd="$PWD"
  cd "$WORKENV_ROOT" || return 1
  if ! git pull; then
    cd "$_envup_pwd" 2>/dev/null || true
    return 1
  fi
  if ! ./install.sh "$@"; then
    cd "$_envup_pwd" 2>/dev/null || true
    return 1
  fi
  cd "$_envup_pwd" 2>/dev/null || true
  # shellcheck source=/dev/null
  source ~/.bashrc
}}
alias git-clear-passwd='git config --global credential.helper store'
if [ "$SPACK_ROOT" != "" ]
then
   if [ "$LOADED_SPACK" != "$SPACK_ROOT" ]
   then
      export LOADED_SPACK="$SPACK_ROOT"
      export SPACK_SKIP_MODULES=1
      source "$SPACK_ROOT/share/spack/setup-env.sh"
   fi
fi
if [ "$LOGGED_IN" != "yes" -a -r ~/.watch-login ]
then
    telegram-send "$HOST-$(date)"
    LOGGED_IN=yes
fi
if [ -r "$WORKENV_ROOT/bin/long-cmd-notify.sh" ]
then
    source "$WORKENV_ROOT/bin/long-cmd-notify.sh"
elif command -v long-cmd-notify.sh >/dev/null 2>&1
then
    source long-cmd-notify.sh
fi

# Share history across live shells on this machine:
#   history -a  append this shell's new lines to ~/.bash_history
#   history -n  pull lines written by other shells into this session
# One PROMPT_COMMAND function so the DEBUG tab-title trap does not treat
# "history -a" as a user command (which left the hourglass stuck).
function __workenv_prompt_command__ {{
  if declare -F __timer_thing_end__ >/dev/null 2>&1; then
    __timer_thing_end__
  fi
  history -a
  history -n
}}
PROMPT_COMMAND=__workenv_prompt_command__
""".format(here=here), file=fd)

vimrc = os.path.join(home, ".vimrc")
if not os.path.exists(vimrc):
    with open(vimrc, "w") as fd:
        print("""
set ai nu ic sw=4 ts=4 expandtab hlsearch linebreak
"colorscheme torture
syn on
filetype plugin indent on
if has("autocmd")
  au BufReadPost * if line("'\\"") > 0 && line("'\\"") <= line("$") | exe "normal! g`\\"" | endif
endif
set ambw=double

" coc.nvim refuses to start if cwd is gone (deleted/renamed dir, bad mount).
" Shells can keep you in a dead PWD; fix that before plugins load.
if !isdirectory(getcwd())
  if isdirectory($HOME)
    silent! execute 'cd' fnameescape($HOME)
  else
    silent! cd /
  endif
endif

" Inline char diffs when available
if exists('+diffopt') && (has("patch-9.1.1243") || has("nvim-0.12"))
    set diffopt+=inline:char
endif

" coc.nvim + clangd (C/C++) via vim-plug when plug is installed
if filereadable(expand('~/.vim/autoload/plug.vim'))
    call plug#begin()
    Plug 'neoclide/coc.nvim', {{'branch': 'release'}}
    call plug#end()

    " Go to definition / type / implementation / references
    nmap <silent> gd <Plug>(coc-definition)
    nmap <silent> gy <Plug>(coc-type-definition)
    nmap <silent> gi <Plug>(coc-implementation)
    nmap <silent> gr <Plug>(coc-references)
    nmap <silent> [g <Plug>(coc-diagnostic-prev)
    nmap <silent> ]g <Plug>(coc-diagnostic-next)
    nnoremap <silent> K :call CocActionAsync('doHover')<CR>

    " Tab completion
    inoremap <silent><expr> <TAB>
          \\ coc#pum#visible() ? coc#pum#next(1) :
          \\ CheckBackspace() ? "\\<Tab>" :
          \\ coc#refresh()
    inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\\<C-h>"
    function! CheckBackspace() abort
      let col = col('.') - 1
      return !col || getline('.')[col - 1] =~# '\\s'
    endfunction
endif

" C/C++ quality-of-life
autocmd FileType c,cpp,cuda setlocal commentstring=//\\ %s

colorscheme LecturedInjury
""".format(here=here), file=fd)

# Install color schemes
vim_dir = os.path.join(home, ".vim", "colors")
if not os.path.exists(vim_dir):
    os.makedirs(vim_dir)
LecturedInjury = os.path.join(vim_dir, "LecturedInjury.vim")
os.makedirs(vim_dir, exist_ok=True)
with open("vim/colors/LecturedInjury.vim") as fdr:
    if not os.path.exists(LecturedInjury):
        with open(LecturedInjury, "w") as fdw:
            fdw.write(fdr.read())

torture = os.path.join(vim_dir, "torture.vim")

if not os.path.exists(torture):
    with open(torture,"w") as fd:
        print("""
" Vim color file
" Maintainer:   Your name <youremail@something.com>
" Last Change:  
" URL:		

" cool help screens
" :he group-name
" :he highlight-groups
" :he cterm-colors

" your pick:
set background=light
hi clear
if exists("syntax_on")
    syntax reset
endif
let g:colors_name="torture"

"hi Normal

" OR

" highlight clear Normal
" set background&
" highlight clear
" if &background == "light"
"   highlight Error ...
"   ...
" else
"   highlight Error ...
"   ...
" endif

" A good way to see what your colorscheme does is to follow this procedure:
" :w 
" :so % 
"
" Then to see what the current setting is use the highlight command.  
" For example,
" 	:hi Cursor
" gives
"	Cursor         xxx guifg=bg guibg=fg 
 	
" Uncomment and complete the commands you want to change from the default.

"hi Cursor		
"hi CursorIM	
"hi Directory	
"See https://github.com/guns/xterm-color-table.vim

hi DiffAdd guifg=white guibg=darkblue
hi DiffAdd ctermfg=white ctermbg=darkblue

hi DiffChange guifg=white guibg=darkred
hi DiffChange ctermfg=white ctermbg=darkred

hi DiffText guifg=white guibg=darkblue
hi DiffText ctermfg=white ctermbg=darkblue

hi italics  guifg=darkblue guibg=black
hi italics  ctermfg=darkblue ctermbg=black

hi quote guifg=green guibg=black
hi quote ctermfg=black ctermbg=black

hi quoteerror ctermfg=black ctermbg=red
hi quixote ctermfg=black ctermbg=cyan
hi letter_a ctermfg=black ctermbg=cyan

hi DiffDelete guifg=white guibg=darkblue
hi DiffDelete ctermfg=white ctermbg=darkblue

hi ErrorMsg	guifg=red term=bold
hi ErrorMsg	ctermfg=red term=bold
"hi VertSplit	
"hi Folded		
"hi FoldColumn	
"hi IncSearch	
"hi LineNr		
"hi ModeMsg		
"hi MoreMsg		
"hi NonText		
"hi Question	
"hi Search		
"hi SpecialKey	
"hi StatusLine	
"hi StatusLineNC	
"hi Title		
"hi Visual		
"hi VisualNOS	
"hi WarningMsg	
"hi WildMenu	
"hi Menu		
"hi Scrollbar	
"hi Tooltip		

" syntax highlighting groups
" term=bold,standout,underline,reverse
hi Comment ctermfg=lightblue term=bold
hi Comment guifg=lightblue term=bold
"hi Constant	
"hi Identifier	
"hi Statement ctermfg=royalblue term=bold
hi Statement guifg=olivedrab3 term=bold
"hi PreProc	
"hi Type		
"hi Special	
"hi Underlined	
"hi Ignore		
"hi Error		
"hi Todo	ctermbg=red term=bold
hi Todo term=standout ctermbg=Yellow ctermfg=Black guifg=Blue guibg=Yellow
hi Search ctermfg=Yellow ctermbg=Black guibg=Black guifg=Yellow
""",file=fd)

gitconf = os.path.join(home,".gitconfig")
if not os.path.exists(gitconf):
    with open(gitconf,"w") as fd:
        print("""
[user]
    email = sbrandt@cct.lsu.edu
    name = Steven R. Brandt
[diff]
  #external = git_diff_wrapper
[pager]
  #diff =
[http]
[merge]
    tool = meld
[branch]
    autosetuprebase = always
#[branch "master"]
#   rebase = true
[credential]
    #helper = osxkeychain
[core]
    #autocrlf = input
  whitespace = -trailing-space,-indent-with-non-tab,-tab-in-indent
    autocrlf = false
    safecrlf = false
	fileMode = false
[credential]
    helper = store
[push]
    default = current
[pull]
    default = current
[alias]
    co = checkout
    vimdiff = -c diff.external=git_diff_wrapper -c pager.diff=0 diff
    clear-passwd = config --global credential.helper store
""".format(here=here),file=fd)

def which(cmd):
    for p in os.environ["PATH"].split(os.pathsep):
        f = os.path.join(p, cmd)
        if os.path.exists(f):
            return (f, cmd)
    return None

installer = which("apt-get")
if installer is None:
    installer = which("dnf")
if installer is None:
    installer = which("yum")
if installer is None:
    installer = which("zypper")

def sucall(cmd):
    if installer is None:
        print("Skipping (no package manager):", cmd)
        return
    if os.getuid() == 0:
        call(cmd)
    elif which("sudo") is not None:
        call(["sudo"] + cmd)
    else:
        print("Skipping (no sudo):", cmd)

def pkg_install(pkg):
    if installer is None:
        print("Skipping package (no package manager):", pkg)
        return
    sucall([installer[1], "install", "-y", pkg])

if which("vim") is None:
    pkg_install("vim")
if which("find") is None:
    pkg_install("findutils")
if which("which") is None:
    pkg_install("which")
if which("file") is None:
    pkg_install("file")
if which("perl") is None:
    pkg_install("perl")
if which("hostname") is None:
    pkg_install("hostname")

# vim-plug (for coc.nvim) — no root required
plug_vim = os.path.join(home, ".vim", "autoload", "plug.vim")
if not os.path.exists(plug_vim):
    try:
        from urllib.request import urlretrieve
        os.makedirs(os.path.dirname(plug_vim), exist_ok=True)
        url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        print("Installing vim-plug ->", plug_vim)
        urlretrieve(url, plug_vim)
    except Exception as e:
        print("WARNING: could not install vim-plug:", e)

# coc-settings.json for clangd (C/C++) — create only if missing
coc_settings = os.path.join(home, ".vim", "coc-settings.json")
if not os.path.exists(coc_settings):
    os.makedirs(os.path.dirname(coc_settings), exist_ok=True)
    with open(coc_settings, "w") as fd:
        fd.write("""{
  "languageserver": {
    "clangd": {
      "command": "clangd",
      "args": ["--background-index", "--clang-tidy"],
      "rootPatterns": [
        "compile_commands.json",
        ".clangd",
        ".git",
        "CMakeLists.txt"
      ],
      "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp", "cuda"]
    }
  },
  "clangd.path": "clangd",
  "clangd.arguments": ["--background-index", "--clang-tidy"]
}
""")
    print("Wrote", coc_settings)

pub_keys=[
"""ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfajFQVE0SSeSSGVWtikBSi02La+0dyxFKBt85R5hcxmWuu1CUbtGnX9+TXPjGwgxVwACH8a0qSshCSupRpaXZcFiTXZWHhriadJpJ06OztJk/aiJ62sqESuWzSrCycZNPzCnPSkchG8Y/XBUJIrDRI4iSsA6VWxdt3sVuUY4uPAocQk1Gu23AHZuNQeWVbOh+MH83lofVOfy2UmDa32rnEhb02iEG+XIhM/UlAnthQn3TxnaMv1yuWLkws2RAckKPAYPIb7pXQx2ZKe+HuJn3TeQLcZnVnYPCv5wEiwZKLZuU//2F13GJlTvHcHRAhSVUPqrRSEno0EfgXqY+LDoN sbrandt@wothw2""",
"""ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvNaz0U/OGtIjTonJVTRgIvPaNsZABZiceO9Mo33SKJHfF+3Sec8ybhVO0f9nTzQ3zhNiVqK45Y3m1wFd8w3EOnNVAjmQUEmjmyXCNYVTkt6IEaRiGNFnUSROYAsNLveVnvryGr725ArDUFqXtqGmdwDPFkxMlrz3f1XY5S1a+NWxF2Si9h2huOzhDRE1+BKPlK0o5P2DDH3nOrUyoaoDzqgieHRmAVpP6zYXIQPPaTGBX/gE4iDFtoNDBuTNqbTWG17JplUGDRELH5hy7KGEXuAzbCgT+LZNU32j+lnPorQXyeRe0yDqCVuCBYFMZ9hJdmbjhPDJxCaYoqpAvo5QAMjIPFISYn7YQIYSDZ8PD4q9HKGThLZ+Ca2R1EHSmekxPtJdjKdwrkLDifOe+IEpsFhwsdbJGCvaJK9GNyKRnB5bNAHY0BZniBZxQo08iR12b+BbvTixvtA3cA7trzQEczOmmig6XrS9iRt1LQdVYMvBxyp8A8Yf2ykZp3JydXRs= sbrandt@Nowhere"""]

ssh_dir = os.path.join(home,".ssh")
if not os.path.exists(ssh_dir):
    os.makedirs(ssh_dir)
os.chmod(ssh_dir,0o0700)
os.chmod(home,0o755)
auth_keys = os.path.join(ssh_dir,"authorized_keys")
auth_keys_c = ""
if os.path.exists(auth_keys):
    with open(auth_keys,"r") as fd:
        auth_keys_c = fd.read()
for pub_key in pub_keys:
    if pub_key not in auth_keys_c:
        with open(auth_keys,"a") as fd:
            print(pub_key,file=fd)
